name: epg酒店源采集合并

on:
  schedule:
    - cron: '5 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install selenium requests futures eventlet pytz lxml

      - name: Run iptv
        run: python ${{ github.workspace }}/epg.py

      - name: 提交更改
        run: |
          git config --local user.email "actions@126.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add generated file" *.xml
          git push -f
